version: '3.5'

services:
  pg:
    image: postgres:12
    environment:
      - POSTGRES_DB=coordinator
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
  coordinator:
    build:
      context: .
      target: dev
    image: coordinator:latest
    command: '/app/bin/dev_entrypoint.sh'
    volumes:
      - ./:/app/
    env_file: docker.env
    ports:
      - '5001:5000'
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-coordinator.settings.testing}
      - PRELOAD_DATA=FAKE
    depends_on:
      - pg
      - redis
  worker:
    build:
      context: .
      target: dev
    image: coordinator:latest
    command: '/app/bin/dev_worker.sh'
    env_file: docker.env
    volumes:
      - ./:/app/
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-coordinator.settings.testing}
    depends_on:
      - pg
      - redis
      - coordinator
  scheduler:
    image: tutum/curl:latest
    command: /bin/bash -c "while true; do sleep 10; curl -s -XPOST coordinator/task-services/health_checks; done"
    depends_on:
      - coordinator

networks:
  default:
    external:
      name: kf-data-stack
