@Library(value="kids-first/aws-infra-jenkins-shared-libraries@feature/add-tests", changelog=false) _
ecs_service_type_1_standard {
    projectName = "kf-api-release-coordinator"
    environments = "dev,qa,prd"
    docker_image_type = "alpine"
    entrypoint_command = "/app/bin/entrypoint.sh" 
    quick_deploy = "true"
    internal_app = "false"
    container_port = "80"
    deploy_scripts_version = "feature/add-tests"
    ecs_service_type_1_version = "feature/add-tests"
    vcpu_container             = "2048"
    memory_container           = "4096"
    vcpu_task                  = "2048"
    memory_task                = "4096"
    health_check_path = "/"
    dependencies = "ecr"
    create_sns_topic = "1"
    create_default_iam_role = "0"
    friendly_dns_name = "release-coordinator"
    additional_ssl_cert_domain_name = "*.kidsfirstdrc.org"
    qa_cidr                    = "0.0.0.0/0"
}
