# Generated by Django 2.0.4 on 2018-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskservice',
            name='author',
            field=models.CharField(default='admin', help_text='The user who created the service', max_length=100),
        ),
    ]
