# Generated by Django 2.0.4 on 2018-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskservice_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskservice',
            name='author',
            field=models.CharField(help_text='The user who created the service', max_length=100),
        ),
    ]
