# Generated by Django 2.0.4 on 2018-07-03 02:29

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180604_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='state',
            field=django_fsm.FSMField(default='waiting', help_text='The current state of the release', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(default='waiting', help_text='The current state of the task', max_length=50),
        ),
    ]
