# Generated by Django 2.0.4 on 2018-08-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180703_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('kf_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(help_text='Time the task was created', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='release',
            name='studies',
        ),
        migrations.AddField(
            model_name='release',
            name='studies',
            field=models.ManyToManyField(help_text='kf_ids of the studies in this release', to='api.Study'),
        ),
    ]
