# Generated by Django 2.0.4 on 2018-08-27 13:16

from django.db import migrations, models
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_study_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='release',
            name='is_major',
            field=models.BooleanField(default=False, help_text='Whether the release is a major  version change or not'),
        ),
        migrations.AddField(
            model_name='release',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, default='0.0.0', help_text='Semantic version of the release', max_length=200, partial=False),
            preserve_default=False,
        ),
    ]
