# Generated by Django 2.0.4 on 2018-08-27 13:16

import coordinator.api.models.release
from django.db import migrations
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_release_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, default=coordinator.api.models.release.next_version, help_text='Semantic version of the release', max_length=200, partial=False),
        ),
    ]
