# Generated by Django 2.0.4 on 2018-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_default_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
