# Generated by Django 2.0.4 on 2018-08-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_study_visible_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.CharField(blank=True, help_text='Release notes', max_length=5000),
        ),
        migrations.AlterField(
            model_name='release',
            name='name',
            field=models.CharField(help_text='Name of the release', max_length=256),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
