# Generated by Django 2.1.11 on 2019-08-15 17:07

import coordinator.api.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181018_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kf_id',
            field=models.CharField(default=coordinator.api.models.event.event_id, max_length=11, primary_key=True, serialize=False),
        ),
    ]
